.PHONY: clean All

All:
	@echo "----------Building project:[ Case8 - Debug ]----------"
	@cd "Case8" && "$(MAKE)" -f  "Case8.mk"
clean:
	@echo "----------Cleaning project:[ Case8 - Debug ]----------"
	@cd "Case8" && "$(MAKE)" -f  "Case8.mk" clean
