#include  WHAT'S NEEDED
using namespace std;

#include "Person.h"

PERSON CLASS MEMBER FUNCTION IMPLEMENTATION

FACULTY CLASS MEMBER FUNCTION IMPLEMENTATION

STUDENT CLASS MEMBER FUNCTION IMPLEMENTATION
